### ISSUE TITLE
dependency is not honored

### ISSUE THREAD

**Issue by sbezverk** [stackanetes/kubernetes-entrypoint#19]
Hello,

I have a dependency for stateful cinder-scheduler set on a service cinder-api. I see that cinder-api container is in init sate, but cinder scheduler is already in running which should not happened. cinder scheduler dependency container tells that the dependency has already been resolved.

Here is the link with all logs we capture for this run. 

http://logs.openstack.org/97/424697/2/check/gate-kolla-kubernetes-deploy-centos-binary-2-helm-entrypoint-nv/54871ee/

Appreciate if somebody could take a look at them. If you have questions, please let me know.
Thank you
Serguei

**Comment by sbezverk** [comment]
Better yet, this logs. 
http://logs.openstack.org/97/424697/3/check/gate-kolla-kubernetes-deploy-centos-binary-2-helm-entrypoint-nv/f687966/
This line shows that cinder scheduler has a dependency:
http://logs.openstack.org/97/424697/3/check/gate-kolla-kubernetes-deploy-centos-binary-2-helm-entrypoint-nv/f687966/console.html#_2017-01-24_17_37_02_030588

This line show that cinder dependency is running when cinder-api pod is still in INit state:

http://logs.openstack.org/97/424697/3/check/gate-kolla-kubernetes-deploy-centos-binary-2-helm-entrypoint-nv/f687966/console.html#_2017-01-24_17_40_40_619265

**Comment by PiotrProkop** [comment]
Thanks, for reporting I'll look into it.

**Comment by PiotrProkop** [comment]
Hi @sbezverk  you are right , there is a bug in this line https://github.com/stackanetes/kubernetes-entrypoint/blob/master/dependencies/service/service.go#L32 . I should have a fix today and prepare new release on Monday. Thanks for reporting this issue.

**Comment by sbezverk** [comment]
Thank you very much for finding it!, Looking forward to the new version.

**Comment by PiotrProkop** [comment]
@sbezverk  https://github.com/stackanetes/kubernetes-entrypoint/pull/21 this is a PR which should fix this bug. The fix was pretty trivial but i also changed go-client version to v.1.5.1.

**Comment by sbezverk** [comment]
Great, please let me know when you post the image, we will need to update our container with it.

**Comment by PiotrProkop** [comment]
HI @sbezverk I just released new version of entrypoint with a bugfix.

**Comment by sbezverk** [comment]
Perfect, thanks a lot! could you please point me to the location of new release?

**Comment by PiotrProkop** [comment]
Sure, https://github.com/stackanetes/kubernetes-entrypoint/releases/download/v0.1.1/kubernetes-entrypoint.
