### ISSUE TITLE
files check

### ISSUE THREAD

**Issue by kfox1111** [stackanetes/kubernetes-entrypoint#23]
In some of my containers, I write out a file instead of a socket. Could we get a feature for blocking until file exists instead of it specifically being a socket?

**Comment by PiotrProkop** [comment]
HI @kfox1111  maybe this dependency name is somehow misleading but it only checks if the file exists and user has permissions to it. So it should work in your case.

**Comment by kfox1111** [comment]
Ah. Cool. Thanks. :)

Could the env var be aliased to DEPENDENCY_FILES too then to make the behavior more apparent?

**Comment by PiotrProkop** [comment]
Sure, I'll do it tomorrow.

**Comment by PiotrProkop** [comment]
hi @kfox1111  i did PR with change , it will be included in next release.
