### ISSUE TITLE
Create Quay repository

### ISSUE THREAD

**Issue by Quentin-M** [stackanetes/kubernetes-entrypoint#3]

**Comment by kfox1111** [comment]
+1. This would allow me to test with it quicker.

**Comment by mzylowski** [comment]
Version for checks and tests is available on quay.io:
https://quay.io/repository/stackanetes/kubernetes-entrypoint?tag=latest&tab=tags

```
docker pull quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
```
